## Required field is added here
namespace: beob2020

name: kubernetes
version: 1.0.4
readme: README.md
authors:
  - Obhade Benard (beny2020@hotmail.com)
description: Role for setting up K8s clusters on prem


# The URL of the originating SCM repository
repository: https://github.com/beob2020/onpremK8s
documentation: https://github.com/beob2020/onpremK8s


homepage: https://github.com/beob2020/onpremK8s
issues: https://github.com/beob2020/onpremK8s/issues

build_ignore: [ ]