---
- name: Clean up Kubernetes Setup
  become: yes
  shell: yes | kubeadm reset

- name: Unhold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubeadm
    - kubectl
    - kubelet
  become: yes

- name: Purge old Kubernetes packages
  apt:
    name:
     - kubeadm
     - kubectl
     - kubelet
     - kubernetes-cni
    state: absent
    purge: yes


- name: Remove generated files and directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - cluster_intialized.txt
    - snap
    - /etc/kubernetes
    - /var/lib/containerd
    - /root/.kube
    - /var/lib/etcd
    - /var/lib/cni
    - /etc/cni
    - /opt/cni
    - /var/run/calico

