---
- name: Unhold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubeadm
    - kubectl
    - kubelet
  become: true
  register: result
  failed_when: false

- name: check result
  ansible.builtin.debug:
    var: result.changed

- name: Clean up Kubernetes Setup
  become: true
  ansible.builtin.shell: |
    set -o pipefail && kubeadm reset --force --cri-socket=unix:///var/run/cri-dockerd.sock
  failed_when: false

- name: Purge old Kubernetes packages
  ansible.builtin.apt:
    name:
     - kubelet
     - kubeadm
     - kubectl
    state: absent
    purge: true

- name: Purge all docker packages
  ansible.builtin.apt:
    name:
     - docker-ce
     - docker-ce-cli
     - containerd
    state: absent
    purge: true
    autoremove: true

- name: Remove generated files and directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - cluster_initialized.txt
    - snap
    - /etc/kubernetes
    - /etc/containerd
    - /etc/cni/net.d
    - /var/lib/containerd
    - /var/lib/docker
    - /var/lib/etcd
    - /var/lib/cni
    - /var/run/docker.sock
    - /var/run/docker.sock
    - /var/run/containerd
    - /run/containerd
    - /etc/sysctl.d/kubernetes.conf
    - /etc/docker
    - /usr/local/bin/cri-dockerd
    - /usr/bin/cri-dockerd
    - /usr/local/bin/cri-docker
    - /etc/systemd/system/kubelet.service.d
    - /etc/systemd/system/cri-docker.service
    - /etc/systemd/system/cri-docker.socket
    - /etc/systemd/system/containerd.service.d
    - /usr/lib/systemd/system/cri-docker.service
    - /etc/systemd/system/multi-user.target.wants/cri-docker.service
    - /root/.kube
    - /opt/cni
    - /var/lib/cni/
    - /var/lib/cni/*
    - /var/etc/cni/
    - /etc/cni/net.d/
    - /usr/local/lib/systemd/system/containerd.service
    - /etc/apparmor.d/docker
    - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - /etc/apt/sources.list.d/kubernetes.list
    - /root/cri-dockerd
    - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - /etc/apt/sources.list.d/apt_kubernetes_io.list
  failed_when: false

- name: Bring cni0 interface down
  become: true
  ansible.builtin.command: ip link delete cni0
  failed_when: false  # Use this if you want to continue even if an error occurs

- name: Bring flannel.1 interface down
  become: true
  ansible.builtin.command: ip link delete flannel.1
  failed_when: false

- name: Bring docker0 interface down
  become: true
  ansible.builtin.command: ip link delete docker0
  failed_when: false

- name: Do apt update
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: true
