---
- name: Unhold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubeadm
    - kubectl
    - kubelet
  become: true
  register: result
  failed_when: false

- name: Remove all Kubernetes running containers
  become: true
  ansible.builtin.shell: |
    set -o pipefail && kubeadm reset --force --cri-socket=unix:///var/run/cri-dockerd.sock
  failed_when: false

- name: Purge old Kubernetes packages
  ansible.builtin.apt:
    name:
     - kubelet
     - kubeadm
     - kubectl
    state: absent
    purge: true

# This is optional, but recommended if you want to reset the iptables rules too
- name: Purge all docker packages
  ansible.builtin.apt:
    name:
     - docker-ce
     - docker-ce-cli
     - containerd
    state: absent
    purge: true
    autoremove: true

# Clean up folders and files that were created by kubeadm init and kubeadm join
- name: Remove generated files and directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - cluster_initialized.txt
    - /etc/cni/net.d
    - /var/lib/docker
    - /var/lib/etcd
    - /var/lib/cni
    - /var/run/docker.sock
    - /var/run/docker.sock
    - /var/lib/kubelet/
    - /etc/sysctl.d/kubernetes.conf
    - /etc/docker
    - /usr/local/bin/cri-dockerd
    - /usr/bin/cri-dockerd
    - /usr/local/bin/cri-docker
    - /etc/systemd/system/kubelet.service.d
    - /etc/systemd/system/cri-docker.service
    - /etc/systemd/system/cri-docker.socket
    - /usr/lib/systemd/system/cri-docker.service
    - /etc/systemd/system/multi-user.target.wants/cri-docker.service
    - /etc/kubernetes/
    - /root/.kube
    - /opt/cni
    - /var/lib/cni/
    - /var/etc/cni/
    - /etc/cni/net.d/
    - /etc/apparmor.d/docker
    - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - /etc/apt/sources.list.d/kubernetes.list
    - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  failed_when: false

- name: Do apt update
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Bring docker0 interface down
  become: true
  ansible.builtin.command: ip link delete docker0
  failed_when: false

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: true
