---
- name: Clean up all the nodes.
  ansible.builtin.include_tasks: cleanup.yml

- name: Install prepare nodes yaml
  ansible.builtin.include_tasks: prepare-nodes.yml

- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.include_tasks: install_k8_components.yml

- name: Install Docker on all nodes
  ansible.builtin.include_tasks: docker_installation.yml

- name: Pull kubeadm images
  ansible.builtin.shell: |
       kubeadm config images pull --cri-socket unix:///var/run/cri-dockerd.sock --kubernetes-version v1.28.0

- name: Restart Kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
    enabled: true
  become: true
