---
# Create admin User
- name:  1) Create a 'default' user
  ansible.builtin.user:
    name: admin
    state: present
    createhome: yes
    shell: /bin/bash

# Enable User to have passwordless sudo
- name:  2) Allow 'admin' to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: 'admin ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# Set Authorized Key taken from the host
- name: 3) Set authorized key took from the host
  authorized_key:
    user: admin
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# 4) Add 'admin' user to sudo group
- name: 4) Add 'admin' user to sudo group
  ansible.builtin.user:
    name: admin
    groups: sudo
    append: yes


# Install Aptitude using apt
- name: 5) Install aptitude using apt module
  ansible.builtin.apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

# Ensuer APT is using HTTPS
- name: 6) Ensure APT is using HTTPS
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-pip
      - python3-setuptools
      - curl
      - golang-go
      - wget
      - lsb-release
      - make
      - git
      - gnupg2
      - software-properties-common
    state: present
    update_cache: yes

 # Reload sysctl
- name: 7) Reload sysctl
  become: true
  ansible.builtin.command: sysctl --system
