---
name: Tests

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
env:
  MOLECULEW_USE_SYSTEM: 'true'
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name:  Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
           yamllint .
